name: Arch Linux CI
on:
  workflow_dispatch:
  push:
    paths:
      - 'PKGBUILD'
  pull_request:
    paths:
      - 'PKGBUILD'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm base-devel  
          useradd build
          chown -R build .
          curl -O https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=qpdfview
          su build -c 'makepkg -s'
          echo "FILE1=$(realpath *.tar.zst)" >> $GITHUB_ENV

          

      - name: Create GitHub Release and Upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          tag_name: qpdfview
          files: |
            ${{ env.FILE1 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
